### ISSUE TITLE
why ctx.caller is not set when service call this.broker.call?

### ISSUE THREAD

**Issue by 0x0a0d** [moleculerjs/moleculer#1046]
I must write 
```js
this.broker.call('another.action', {}, { caller: this.name })
```
I just want to known why `ctx.caller` is not set automatically?

**Comment by intech** [comment]
> I must write
> 
> ```js
> this.broker.call('another.action', {}, { caller: this.name })
> ```
> 
> I just want to known why `ctx.caller` is not set automatically?

Use `ctx.call()`

**Comment by ccampanale** [comment]
The `ServiceBroker` instance available on a `Service` instance's `this.broker` may be brokering communication to multiple service instances in the local process. Using `this.broker.cal()` to call another action doesn't specify which service is making the call so the broker creates a fresh `Context` object. This is why it requires providing the caller in the options parameter.

As @intech pointed out, the `ctx` object provided to an action handler will be populated with information about the receiving service as the local broker knows which service was picked to handle the incoming request. Therefore, using `ctx.call()` will populate this information for you.

If you find yourself doing this frequently, may I suggest simply creating a function which could be shared across multiple service definitions as a method to simplify this?

For example:

```ts
import Moleculer from 'moleculer';

export function call<T = any, P = any>(
  this: Moleculer.Service,
  action: string,
  params: P,
  opts?: Moleculer.CallingOptions,
) {
  this.broker.call<T, P>(
    action,
    params,
    {
      ...opts,
      caller: this.name,
    }
  );
}
```

The above function could be provided on a service schema as a method and support a simple `this.call()` from the service which would automatically populate the caller.

**Comment by intech** [comment]
I do not know what problem you are trying to solve. But it is not recommended to manually specify the caller.

**Comment by ccampanale** [comment]
@intech Good question, I was assuming it had something to do with metrics and/or tracing...

**Comment by 0x0a0d** [comment]
`ctx.call` is available only when I make a call in `action`. In `methods`, or `started`, I have access to `this.broker` and I must manually set `options.caller`, I wonder why molculer's broker can't be set up by itself

**Comment by intech** [comment]
@0x0a0d I double-checked everything. My concerns were related to the use of `caller` in middlewares, I thought that specifying this parameter myself in options could break checks and cause problems.
But after examining carefully all the code where the `caller` is used, I did not find confirmation. But I found that it is processed in `opts` in `Context` and this was added separately.
I missed this point, so I apologize for the false information. Everything should work correctly!

Now I will answer your question about the automatic installation of `caller` in requests for` broker.call`, this cannot work, because `caller` must contain the name of the service and the name of the action from which the call is originating, and in` broker.call` we do not we know. It can be used in middlewares as well.
