### ISSUE TITLE
0.14.22 Release Broke Service.mergeSchemas() and others

### ISSUE THREAD

**Issue by SnickerChar** [moleculerjs/moleculer#1124]
The 0.14.22 release broke the Service.mergeSchemas() method, likely along with all other static members of the Service class. We just updated to 14.22 from 14.21, and started getting errors at startup like this:

```
`[2022-08-16T17:52:02.527Z] DEBUG insight-platform-insight-platform-combined-server-deploymef5hss-46/BROKER: Broadcast '$broker.error' local event.
[Runner] moleculer_1.Service.mergeSchemas is not a function TypeError: moleculer_1.Service.mergeSchemas is not a function
    at AggregatorService.parseServiceSchema (/app/node_modules/moleculer-ioc/src/index.ts:32:34)
    at new SecureService (/app/packages/security/src/SecureService.ts:46:8)
    at new AggregatorService (/app/packages/aggregator/src/aggregator.service.ts:24:1)
    at ServiceBroker.loadService (/app/node_modules/moleculer/src/service-broker.js:784:11)
    at /app/node_modules/moleculer/src/service-broker.js:757:59
    at Array.forEach (<anonymous>)
    at ServiceBroker.loadServices (/app/node_modules/moleculer/src/service-broker.js:757:34)
    at MoleculerRunner.loadServices (/app/node_modules/moleculer/src/runner.js:348:17)
    at MoleculerRunner.startBroker (/app/node_modules/moleculer/src/runner.js:485:8)
    at /app/node_modules/moleculer/src/runner.js:504:21`
```

This PR introduced the change: https://github.com/moleculerjs/moleculer/pull/1098.

The module that is complaining is my own moleculer-ioc (https://github.com/csibbach/moleculer-ioc), a pet project, but it requires ^0.14.17, and introduces an extension of the Service class IOCService. I will update the module, but it is unfortunate that a breaking API change was introduced in a bugfix version.

**Comment by intech** [comment]
@SnickerChar Sorry for breaking your package. Changes were needed to use the ServiceFactory. Previously, this was impossible due to static methods and the impossibility of overriding them.

You just need to replace from `Service.mergeSchemas` to `this.mergeSchemas` to restore your module.
https://github.com/csibbach/moleculer-ioc/blob/develop/src/index.ts#L32

Thank you for your contribution to the ecosystem!

**Comment by SnickerChar** [comment]
Thank you! I understand why the change was needed, and it would be undesirable to mint a new major version just for that. I can't think of a better way to do this. I created the issue mainly to help anybody else that might encounter this.

**Comment by icebob** [comment]
@SnickerChar thank you for the report and sorry for your inconvenience. You are right, it breaks if somebody uses it in libs or projects. 
When I merged the PR, I thought these methods were not used directly because they were not published in documentation.

@intech if it causes more problems later, we should put back the original code and somehow solve that both implementations can work side by side.
