### ISSUE TITLE
Moleculer causes typescript errors with typescript version 4.8.2

### ISSUE THREAD

**Issue by SockeThe2nd** [moleculerjs/moleculer#1129]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [X] I am running the latest version
- [X] I checked the documentation and found no answer
- [X] I checked to make sure that this issue has not already been filed
- [X] I'm reporting the issue to the correct repository

## Current Behavior

The currents version of moleculer throws a typescript error when compiling with the current 4.8.2 version of typescript.

## Expected Behavior

The build should pass without errors

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. update typescript dependency of moleculer to 4.8.2  via `npm i typescript@4.8`
2. run the ts-test `npm run test:ts

The tests will fail. Trying to build a project with ts 4.8 also fail.

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.14.23 (current)
* Typescipt version: 4.8.2
* NodeJS version: 14.18.1
* Operating System: Ubuntu 20.01 under WSL2 in Win10

### Failure Logs
```
index.d.ts:757:3 - error TS2416: Property 'settings' in type 'Service<S>' is not assignable to the same property in base type 'ServiceSchema<ServiceSettingSchema>'.
  Type 'S' is not assignable to type 'ServiceSettingSchema | undefined'.
    Type 'S' is not assignable to type 'ServiceSettingSchema'.

757   settings: S;
      ~~~~~~~~

  index.d.ts:749:16
    749  class Service<S = ServiceSettingSchema> implements ServiceSchema {
                       ~~~~~~~~~~~~~~~~~~~~~~~~
    This type parameter might need an `extends ServiceSettingSchema` constraint.
  index.d.ts:749:16
    749  class Service<S = ServiceSettingSchema> implements ServiceSchema {
                       ~~~~~~~~~~~~~~~~~~~~~~~~
    This type parameter might need an `extends ServiceSettingSchema | undefined` constraint.


Found 1 error in index.d.ts:757
```

**Comment by shawnmcknight** [comment]
I agree that having `S extends `ServiceSettingSchema` in all of these locations is a more correct interpretation of what the generic should be since the internal properties are present on the value of `settings` even if the consumer specified an interface that does not include them.

However, this change is likely to introduce a breaking change for anyone that did not previously pass a generic argument that extended `ServiceSettingSchema`.  This would have worked fine before, although the internal properties would not have been accessible on `settings`.

I'm wondering if there is possibly a 2-stage approach to getting around the TS errors -- one breaking and one not.  I haven't tried it out, but I was thinking that if:
```
class Service<S = ServiceSettingSchema> implements ServiceSchema
```

was changed to:
```
class Service<S = ServiceSettingSchema> implements ServiceSchema<S>
```

if that would prevent the TS errors while preventing a breaking change.  If that works, that could be merged in immediately without causing an issue for users.

The changes that are part of this PR could then be released at a later date when a breaking change version of moleculer is published.  I'm not sure when a breaking change version is intended to be published next, but this might allow for a better staging of that change.
