### ISSUE TITLE
Metric enhancements

### ISSUE THREAD

**Issue by icebob** [moleculerjs/moleculer#219]
Branch: [metrics2](https://github.com/moleculerjs/moleculer/tree/metrics2)

**Metric event payload changes**
- [ ] add `service` as service name
- [ ] add `type` as event type. Values: `call` (current), `custom` - user generated event
- [ ] add `error.data`
- [ ] _add `error.stack` (not sure, it can generate big overhead)_

**New Context method to create custom metric spans**
- [ ] `ctx.metric(name, params);` - start a new metric span event

**Example**
```js
{
    actions: {
        async update(ctx) {
            // ... Do something
            const span = ctx.metric("update-db", { id: 3 });
            
            await this.db.updateById(3, {});
            
            span.end();
            // ... Do something
        }
    }
}
```

**Comment by intech** [comment]
Hi, @icebob ! :hand: 

Using the [Elastic APM Agent](https://github.com/elastic/apm-agent-nodejs), I got the following results:

![apm-1](https://user-images.githubusercontent.com/451306/39245093-6103eb28-489b-11e8-9ac3-66a70de96b3c.png)
![apm-2](https://user-images.githubusercontent.com/451306/39245091-60e1b4cc-489b-11e8-8f37-5ff415b7c50b.png)
![apm-3](https://user-images.githubusercontent.com/451306/39245090-60c05ec6-489b-11e8-8c04-32649f5a6cb2.png)
![apm-4](https://user-images.githubusercontent.com/451306/39245089-60a15526-489b-11e8-9c88-77af49963a06.png)
![apm-5](https://user-images.githubusercontent.com/451306/39245088-607fa1ec-489b-11e8-8008-dfcbf283eee9.png)
![apm-6](https://user-images.githubusercontent.com/451306/39245087-605d43d6-489b-11e8-8482-91fa4cd8daae.png)
![apm-7](https://user-images.githubusercontent.com/451306/39245086-6039eff8-489b-11e8-97bd-555245678826.png)

:exclamation: The data collected through the metric events span and processed by the [moleculer-elastic-apm](https://github.com/intech/moleculer-elastic-apm).
See what I found problems with the categorization of data using the molecules [molecular-web](https://github.com/moleculerjs/moleculer-web), [molecular-bull](https://github.com/moleculerjs/moleculer-addons/blob/master/packages/moleculer-bull) and [molecular-elasticsearch](https://github.com/moleculerjs/moleculer-addons/blob/master/packages/moleculer-elasticsearch)

![2018-04-25 15-20-10](https://user-images.githubusercontent.com/451306/39245449-83106272-489c-11e8-81e6-00b5458dd894.png)

![2018-04-25 15-19-59](https://user-images.githubusercontent.com/451306/39245451-8334d0f8-489c-11e8-83c2-bcf4e9cad19e.png)

:point_up_2: Look at the module built into the Elastic APM that defines the operations of ioredis, pg and elasticsearch packages. They look good.
Internal calls to microservices are not such nice types and names in my report.
This information will help to come up with an excellent solution.
I'll be glad to help! :wink:

**Comment by icebob** [comment]
Thank you!

Yes, it looks very pretty!

**Comment by icebob** [comment]
@intech I'm starting to rewrite tracing in Moleculer. What are your suggestions to be it better?

**Comment by intech** [comment]
@icebob I will describe the thoughts that I see. But I'm not so good at understanding all the internal processes of the moleculer and I can not say about the correctness of my decisions.
Think about the best solution based on your expert experience.

1. The most important thing I encountered is the division of transactions.
We need to build logical levels so that the moleculer-web participates in these measurements as a single transaction from the first http(s) call and until the last service response.
The task is very much and I did not have time to study the problem in detail.
According to my tests, you need to get more information from moleculer-web in the metric https://github.com/moleculerjs/moleculer-web/blob/master/src/index.js#L667 information about the query parameters before calling the broker. Also, the moleculer-web response must conform to the HTTP standard (200 OK) and contain the response body from the service. In this way, I can supplement the requests to the service in a few span with information about the request itself.

2. You must store the chain of the route node1 (v1.api.get) -> node4 (elasticsearch.search) -> node9 (redis.cache) in the metric to build the query tree.

3. How do you look at adding standard events besides tracing, which will show service calls by name with parameters. I've seen a nearby issue about hooks, but they only solve the problem sequentially and do not decide if to do a parallel task.

**Comment by icebob** [comment]
Hi @intech,
yesterday I've checked the Elastic APM docs & sources. I think it is not a good choice to monitoring & tracing microservices. The "only-one-active-transaction" concept can't trace microservices properly. NodeJS executes multiple requests in parallel, so you have a lot of unfinished transactions because a new `startTransaction` overwrites the previous active transaction. 
On the other hand, you can't share transactions between processes. They can run only on the process where they've been started.
Finally, the spans have no parents (just the transaction as a root). So you can't build a trace tree from spans what Zipkin & Jaeger can do it. Moreover, you can't store this information in spans.

These issues are in the Elastic APM server & clients, what we can't solve it in a Moleculer tracing module.
Btw, I like that there is a free APM solution with a nice dashboard, but I think it should evolve to support microservices architecture tracing.

**Comment by intech** [comment]
@icebob you are right! Now I know which direction to continue developing apm elastic and moleculer dashboard.
