### ISSUE TITLE
BrokerOptions: what is the transit property?

### ISSUE THREAD

**Issue by benjsicam** [moleculerjs/moleculer#302]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

### Context

* Moleculer version: 0.12.8
* NodeJS version: 10
* Operating System: OS X 10.13.5

### Question

There is a transit property on the BrokerOptions TypeScript definition that isn't documented on http://moleculer.services/0.12/docs/broker.html#Broker-options. What is it for? Is the documentation or the TypeScript definition not updated?

**Comment by icebob** [comment]
It's missing from the docs. It has only a `maxQueueSize` [property](https://github.com/moleculerjs/moleculer/blob/master/src/service-broker.js#L67). It's a protection against inordinate memory usages when there are too many outgoing requests. So it's a limit that node process can't reach the 1.4GB mem limit and can't crash due to many waiting contexts. 
The default value is 50.000. So if there are more than 50k outgoing live requests, the new requests will be rejected with `QueueIsFullError` error.
