### ISSUE TITLE
Official Typescript project template

### ISSUE THREAD

**Issue by icebob** [moleculerjs/moleculer#307]
**Describe the solution you'd like**
Would be good an official project template with Typescript. I have not enough experience to create it. Can somebody help me with it?

Base template: https://github.com/moleculerjs/moleculer-template-project

Thank you!

**Comment by DrecDroid** [comment]
Ok, this is what I have:
https://github.com/DrecDroid/moleculer-typescript-example

I've discovered moleculer two days ago so I don't know if molecular-runner would work with typescript files because typescript imports works differently depending on how tsconfig.json paths are configured. The example works programatically, it tries to import from SERVICE_PATH env var in the `./broker.ts` file.

You can run it like with the cli template:
`docker-compose up -d --build`

There is this other way that works by defining the compilation with tsc in the dockerfile and setting the SERVICEDIR to the `outDir` defined in `tsconfig.json` file, this way it could work with moleculer-runner and compilations errors would be shown during docker building instead of during runtime.

Thanks for this awesome project btw!

**Comment by icebob** [comment]
Great, thanks, I'm checking!

**Comment by icebob** [comment]
Would be better to use runner to start broker & services like in JS template. You can start it as 

`ts-node ./node_modules/moleculer/bin/moleculer-runner.js --repl services`

**Comment by icebob** [comment]
Or `node -r ts-node/register node_modules/moleculer/bin/moleculer-runner --hot --repl --mask **/*.service.ts services`

**Comment by DrecDroid** [comment]
I've create this other repo with another approach and this time starting from a clean project generated from the cli.

https://github.com/DrecDroid/moleculer-typescript-like-cli

Differences from the javascript template:
- Requires `@types/node`, `typescript` as dependencies, they can't be devDependencies otherwise it will not compile on production
- The services and the moleculer.config files are all in typescript
- Adds a typescript compilation step in Dockerfile, because no `outDir` is specified in `tsconfig.json` the compiled files will be placed alongside the originals inside the docker container. This makes everything work like in the original javascript template.

**Comment by icebob** [comment]
Great, but please add NPM script to dev & compile

**Comment by katsanva** [comment]
https://github.com/katsanva/typescript-moleculer-bootstrap please check this

**Comment by icebob** [comment]
Thanks @katsanva, at first I try to use @DrecDroid repo because it's more similar as JS project template.

**Comment by NsSumse** [comment]
In the examples we don't have a method call. When we add a method and want to call it with a this.[methodname](), typescript will throw an error, cause typescript doesn't know the method

**Comment by keko950** [comment]
@DrecDroid Sadly your template is not working (At least, not for me). Anyone working on this?

**Comment by DrecDroid** [comment]
It doesn't work with npm commands just with docker

**Comment by faeron** [comment]
I just ported moleculer-template-project to typescript in my repo https://github.com/faeron/moleculer-template-project-typescript and it should work the same as the official template.

What did I test/should work?
- generation of new template with moleculer-cli with existing questions (as transporters only nats and amqp was tested manually, the rest should work too because nothing there has been touched)
- debug of services and tests in vscode (launch.json)
- all npm scripts (test,ci,build,start)
- docker build
- docker-compose

**Comment by keko950** [comment]
This is great! I'm testing this today!
i will give feedback soon as possible, thanks i really was interested in this!

**Comment by icebob** [comment]
Nice job @faeron, i will also check it!

**Comment by faeron** [comment]
Thanks for the feedback.
1. I could not reproduce it (for me the script used the --mask option correctly), but with your suggested script it is also working, so I will use this.
2. I will try to fix that somehow. Problem seems to be that only moleculer-runner itself uses the option and cannot handle ``.ts`` files.
A workaround/simple fix could be to compile the config file before running moleculer-runner and provide the file with ``.js`` extension. But I would like to have a way without cluttering the project folder.

**Comment by tcaraccia** [comment]
Did you tried adding -r tsconfig-paths/register to your ts-node ?

**Comment by icebob** [comment]
2. https://github.com/moleculerjs/moleculer/commit/0b9a7208a088d63aa58ae9ff6c787993c1027e54 will allow loading ts file too with `"dev": "ts-node ./node_modules/moleculer/bin/moleculer-runner.js --hot --repl --config moleculer.config.ts services/**/*.service.ts"` script.

**Comment by faeron** [comment]
Ok, very nice. Both issues fixed then. Do you guys have anything else that needs a change?

**Comment by faeron** [comment]
A [project-template](https://github.com/moleculerjs/moleculer-template-project-typescript) is now in place. I guess this issue can be closed?

**Comment by icebob** [comment]
Yes. Thanks @faeron

**Comment by edurdias** [comment]
> 1. [0b9a720](https://github.com/moleculerjs/moleculer/commit/0b9a7208a088d63aa58ae9ff6c787993c1027e54) will allow loading ts file too with `"dev": "ts-node ./node_modules/moleculer/bin/moleculer-runner.js --hot --repl --config moleculer.config.ts services/**/*.service.ts"` script.

@icebob has this commit been released to npm?

**Comment by icebob** [comment]
Not yet. I will release it this week.

**Comment by Elvenisboy** [comment]
@faeron when us `npm run dev`, I can't open a dev server and get a error:

```
Not supported file extension: .ts Error: Not supported file extension: .ts
```

I think, ts filecan't load by `"ts-node ./node_modules/moleculer/bin/moleculer-runner.js --hot --repl --config moleculer.config.ts services/**/*.service.ts`

**Comment by faeron** [comment]
@Elvenisboy as stated in some comments above, the typescript template is dependent of the newer release of moleculer-runner (which is not out yet). 

> 1. [0b9a720](https://github.com/moleculerjs/moleculer/commit/0b9a7208a088d63aa58ae9ff6c787993c1027e54) will allow loading ts file too with `"dev": "ts-node ./node_modules/moleculer/bin/moleculer-runner.js --hot --repl --config moleculer.config.ts services/**/*.service.ts"` script.

**Comment by Elvenisboy** [comment]
@faeron OK 👌 , I know. Thanks for your help 😋

**Comment by muenalan** [comment]
Sorry, but did somebody get methods to run in actions ? For me TS2339 is thrown, as Typscript will not understand that the methods are injected ?!
