### ISSUE TITLE
Fetching data from multiple models in single service.

### ISSUE THREAD

**Issue by janibhautik** [moleculerjs/moleculer#368]
**I have created services named "users" (model properties: id,name,email) and "posts" (model properties: id, description,user_id) where posts are created by users.
Using mysql as DB and taken one of examples ref. given in documentation as reference. The services are working perfectly individually.

Now, I want to fetch list of posts with their creater details then How can I do this**. 

Tried using "Populates" but it does nothing. Used same syntax as given in the documentation but nothing happens.

Strange that I dont find any example of moleculer using mysql. Also not found anything related to "Models" in moleculer Documentation.

**Comment by keko950** [comment]
As far i know you can't access multiple models from the same service. One service, one model.
So, in order to fetch data my guess is that you have to call the service which uses that model. 
You have an example in docs:
![screenshot_20180821_140200](https://user-images.githubusercontent.com/9590497/44400243-ccfb8a00-a54a-11e8-8601-607e5f293a03.png)

Maybe there is another way, dunno, hope it helps

**Comment by janibhautik** [comment]
Hi @keko950, Thanks for helping. But according to these example, I have to make calls for each and every entities that are related to each other that leads to make so many calls while fetching a list of entities.

**Comment by keko950** [comment]
Hi again @janibhautik !
Moleculer does implement this microservice pattern (as @icebob 
 told me lately) https://microservices.io/patterns/data/database-per-service.html
As the doc says: 
**Implementing queries that join data that is now in multiple databases is challenging.**

There are various solutions:

**API Composition** - the application performs the join rather than the database. For example, a service (or the API gateway) could retrieve a customer and their orders by first retrieving the customer from the customer service and then querying the order service to return the customer’s most recent orders.

**Command Query Responsibility Segregation (CQRS)** - maintain one or more materialized views that contain data from multiple services. The views are kept by services that subscribe to events that each services publishes when it updates its data. For example, the online store could implement a query that finds customers in a particular region and their recent orders by maintaining a view that joins customers and orders. The view is updated by a service that subscribes to customer and order events.

**Comment by katsanva** [comment]
@keko950 definitely what are you asking about is [population](https://github.com/moleculerjs/moleculer-db/tree/master/packages/moleculer-db#populating), and I can guarantee that it's working - check your population setup few more times.

Your configuration should look like 

```js
{
    settings: {
        populates: {
            user_id: 'users.get',
    },
}
```

**Comment by keko950** [comment]
Interesting, not much about this on the docs so i didn't check it before.
Thanks @katsanva , anyway, the OP @janibhautik said that populates is not working, maybe post your code to check if something wrong?

**Comment by janibhautik** [comment]
I have created services named: "product" and "product_images" having models with the same name. While fetching the product images, I also want to fetch product's name for product_id value.

![2018-08-24_0902](https://user-images.githubusercontent.com/13635114/44563631-a0c74f80-a77c-11e8-907b-b7cc341dfa5d.png)

This is how I used populates. While the output gives product_id as undefined:
![2018-08-24_0908](https://user-images.githubusercontent.com/13635114/44563780-67431400-a77d-11e8-9e00-bd9055d91f14.png)

**Comment by icebob** [comment]
@janibhautik what is the exact use-case? Because you post result from db and not from service result.

**Comment by janibhautik** [comment]
Hi @icebob , I want to populate the product details while calling product_image list. Above is the output I am getting while using the above code. I am getting product_id field "undefined" in console. The browser output is :

![2018-08-28_0903](https://user-images.githubusercontent.com/13635114/44699523-44c53980-aaa2-11e8-9677-05f218e31465.png)

**Comment by katsanva** [comment]
@janibhautik  @keko950 probably you need to set projection for that fields. My code:

Service:
```ts
export default <Moleculer.ServiceSchema>{
  name: 'very-important-service',
  mixins: [
    DbService,
  ],
  model: VeryImportantServiceModel,
  adapter: new MongooseAdapter(config.get('mongodb')),
  settings: {
    populates: {
      creditor: 'profiles.get',
      debtor: 'profiles.get',
    },
  },
};
```
Somewhere in other services:
```ts
const params = {
        fields: [
           'debtor',
           'creditor',
        ],
        populate: [
          'creditor',
          'debtor',
        ],
};

const result = await ctx.broker.call('very-important-service.list', params);
```

**Comment by icebob** [comment]
Did you add the `product_id` field to the `fields` list in the service settings?

**Comment by janibhautik** [comment]
@icebob , Yes. My final code looks like this:

![2018-08-29_1116](https://user-images.githubusercontent.com/13635114/44767892-2ed87700-ab7d-11e8-884e-9bdf94eefca7.png)

**Comment by janibhautik** [comment]
Yes @icebob , my latest code looks like this:

![2018-08-29_1116](https://user-images.githubusercontent.com/13635114/44767957-562f4400-ab7d-11e8-9f62-16d92d0f40ef.png)

**Comment by icebob** [comment]
I have no other idea. If you can create a reproduce repo I will check it.

**Comment by hupptechnologies** [comment]
If someone facing same situation in sequelize then i have found solution for it.

I was faced same situation and now i come into the solution that i can run raw queries too, so i did like below to fetch data from multiple tables.

### Join Example
```
this.model.sequelize.query("SELECT table1.*, table2.column_name as custom_name FROM table1 INNER JOIN table2 ON table1.column_name = room_types.column_name").then(result => {
    console.log(result)
});
```

### Group By Example
```
let records = await this.model.findAll({
	where,
	group: ["column_name"]
});
```

So i am using model instance directly instead of molueculer db adapter in some of cases like above.
