### ISSUE TITLE
Runner misconfiguration

### ISSUE THREAD

**Issue by katsanva** [moleculerjs/moleculer#401]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository

## Expected Behavior
```sh
> SERVICES=foo node ./node_modules/.bin/moleculer-runner -H -c moleculer.config.dev.json dist/services

[2018-10-26T13:42:54.388Z] DEBUG local-60083/BROKER: Load service 'foo.service.js'...
[2018-10-26T13:42:55.469Z] DEBUG local-60083/BROKER: Watching 'foo' service file...
```

## Current Behavior

```sh
> SERVICES=foo node ./node_modules/.bin/moleculer-runner -H -c moleculer.config.dev.json dist/services

[2018-10-26T13:44:30.408Z] WARN local-60107/BROKER: There is no matched file for pattern: 'foo'
```
## Failure Information

Runner skips folder provided folder throuh cli, expects `SERVICEDIR` env variable.

### Steps to Reproduce

See current behaviour

### Context

* Moleculer version: 0.13.3
* NodeJS version: 10.12.0
* Operating System: OS X

### Failure Logs
```

```

**Comment by icebob** [comment]
Thanks, I will check it.

**Comment by icebob** [comment]
It is not a bug, just a misunderstanding.
The Runner option handling has been changed in 0.13.0 version: https://github.com/moleculerjs/moleculer/blob/master/CHANGELOG.md#load-services-also-with-glob-patterns
You should use filenames, directory names or glob patterns in Runner arguments. But if you define `SERVICES` env var, it overwrites the arguments. The reason is that you can use different arguments at developing, but in production, you can overwrite it with the environment variables.

E.g define `npm start` script as `moleculer-runner services/**/*.js` because you should load all services at developing. And when you deploy the project you just overwrite this parameter with env var as `SERVICES=services/user.service.js`

So in your case, you should use this form:
```
SERVICES=dist/services/foo node ./node_modules/.bin/moleculer-runner -H -c moleculer.config.dev.json
```
or 
```
SERVICEDIR=dist/services SERVICES=foo node ./node_modules/.bin/moleculer-runner -H -c moleculer.config.dev.json
```

**Comment by katsanva** [comment]
Thanks
