### ISSUE TITLE
How to create multiple service broker with moleculer-runner?

### ISSUE THREAD

**Issue by thailan** [moleculerjs/moleculer#455]
Hello , thank you very much for this awesome framework. My question is , how to create multiple broker with moleculer-runner?I dont want to create manually ServiceBroker, I want to use moleculer runner aproach.  I mean moleculer.config.js exports 1 broker , how can I create multiple broker , and assign specific service to specific broker? 
 
sorry for my english, have a nice day

The structure I want to achieve 

|Node Instance A  | Node Instance B |
| ------------- | ------------- |
| Broker A | Broker B |
| Service A1, Service A2  | Service B1, Service B2 |

**Comment by icebob** [comment]
With parameters:
- on NodeA: `moleculer-runner services/a1.service.js services/a2.service.js`
- on NodeB: `moleculer-runner services/b1.service.js services/b2.service.js`

Or you can use env vars:
- `$ SERVICES=services/a1.service.js,services/a2.service.js moleculer-runner`
- `$ SERVICES=services/b1.service.js,services/b2.service.js moleculer-runner`

**Comment by thailan** [comment]
Thank you for your answer ,  so I understand that  I should start nodes separately right?  I am trying to understand concept.   What is the correct way to start 2 or more  Instance? 
I created 2 seperate moleculer project template , start them separately with npm run dev 
when I check **nodes** on  moleculer-runner console , I cant see Node Instance B , also checked dcall command but it gave an error , can you give us example please , thank you

**Comment by icebob** [comment]
Yes, if you want to start more brokers on the same node, you should start them separately. When I develop I'm using multiple terminals to start multiple brokers, so you have multiple console logs & REPL console and you can better detect the issues.
Are you trying on Windows? Because you can't start multiple "blocking" process with one command using `&&`. On linux you can use a simple `&` which doesn't wait for the process will be exited or use some external cli tool, like https://github.com/flesler/parallel

The other way is that you create only one project repo which contains all services and you start them separately only in production with `SERVICES` env var.

**Comment by thailan** [comment]
My target is ( and what I understand about concept) , run some services on one node instance and some services on other node instance and communicate with each other by brokers. 
I am trying to assing single seperate nodes for each project but want them communicate with each other. Maybe I misunderstand of concept.

**Comment by icebob** [comment]
I see, it's a regular concept, but it doesn't mean that you can't use one repo. Check this example: https://github.com/moleculerjs/moleculer-examples/tree/master/blog
It's a repo which contains all services, so easy to develop because you starts all services locally.
In production, you can use Docker containers where you can separate services to multiple containers/node and they communicates each others via NATS transporter.

Here you can see you can define multiple services what you want to load on the nodes: https://github.com/moleculerjs/moleculer-examples/blob/master/blog/docker/mixed/docker-compose.yml#L34

**Comment by icebob** [comment]
Other example: https://github.com/nickreese/moleculer-docker-development

**Comment by thailan** [comment]
Thank you very much its worked  , and I understand the concept.

**Comment by Murzilka** [comment]
> Other example: https://github.com/nickreese/moleculer-docker-development

This link is broken
