### ISSUE TITLE
Actions visibility - possible security breach

### ISSUE THREAD

**Issue by flaviocordova** [moleculerjs/moleculer#466]
**Is your feature request related to a problem? Please describe.**
the default visibility to an action is published, what I think could cause serious security breaches once gateway doesn't take care of whitelisting exactly what it needs. Having the default as public would protect services by default and then only those really needed would be exposed.

Notice that any gateway in any node could cause a full exposition of all services.

I understand it's potentially breaking change, so some things could be done to reduce impact:
1) be able to turn default visibility in broker and service (to prevent having to set it in every single action created).
2) deprecate methods and add warning to let developers know things will be more restrictive in the future
3) Enable gateway to automatically publish actions when visibility is not set *once they are whitelisted* (not a good practice, should be also configured and warned, but could work as temporary strategy.

**Comment by kevyworks** [comment]
I think you can easy do this w/ mixins and use that mixins to set your common actions default `visibility: "public"` https://moleculer.services/docs/0.13/actions.html#Action-visibility -- The thing here is its micro services, and I think its flexible enough and design choices by the author is correct.

**Comment by giang12** [comment]
I think @flaviocordova is asking to have an options to change `The default value` which is null (means published) due to backward compatibility.` 

we can change moleculer-web https://github.com/moleculerjs/moleculer-web/blob/28f9e1c61cd6f6cedac8a397c35cf2fa3aab6ed6/src/index.js#L421 

or we can default all actions `visibility` to `public` instead of null. I dont believe theres a convenient way to do this now
