### ISSUE TITLE
regression - change to PromiseType from Bluebird is not compatible

### ISSUE THREAD

**Issue by fugufish** [moleculerjs/moleculer#482]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x ] I am running the latest version
- [ x] I checked the documentation and found no answer
- [x ] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository

## Expected Behavior
Promises should be compatible with Bluebird. Changing to PromiseTypeConstructor introduced incompatibility with the previous version

## Failure Information
This change: https://github.com/moleculerjs/moleculer/commit/ea3c8193259a00c8cd42fb3826756593afa51690#diff-b52768974e6bc0faccb7d4b75b162c99

**Comment by icebob** [comment]
Please discuss it with @snnsnn 

*By the way, I don't know how it is working in other projects, but I see that somebody sends a d.ts improvement PR, I merge it, release it, and it causes problems for someone else. Same issue in fastest-validator project. I don't know, how it can be controlled properly.*

**Comment by fugufish** [comment]
yah, .tds is probably hard I would suggest having the pr require at least a comment that backwards compatibility was checked, and maybe have an rfc for known TS users to check if it breaks in master. I know there is another breakage but I didn't have time to look into it.

**Comment by snnsnn** [comment]
Sorry for your trouble. I changed the definition in a way that works for both native promises and promise libraries like bluebird. Previously native promises were not supported. 

Since [Bluebird](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/bluebird/index.d.ts) also implements PromiseLike constructor, fixing the issue should be easy:

`declare class Bluebird<R> implements PromiseLike<R>`

**Comment by fugufish** [comment]
I understand that, the problem is that patch level  update (in this case from 0.13.4 > 0.13.4) is not backwards compatible. From my understanding, @icebob can correct me if I'm wrong, but we are supposed to be able to trust backwards compatibility between patch level updates.

**Comment by icebob** [comment]
Yes, we should but I'm not using Typescript, I can't review the d.ts PRs whether it's backwards compatible or not.

@snnsnn please create a fix PR and I will release it as soon as I can.

**Comment by snnsnn** [comment]
Hi everyone,

I am not sure ts.d files should dictate major version change because there is no way to remove dependency to bluebird from type definitions without major version bump. We could use union of Bluebird and PromiseLike but that does not make sense, since it will be union of a type with itself.

But if we bump up the major version, that does not make sense either because library remains same, no actual API change took place. Plus, moleculer itself has not reached version 1.0.

Also renaming type Blubird to PromiseLike should not break anything because Blubird satisfies PromiseLike. So, it is should not cause backward compatibility issue. 

I think we need more opinions on this. @faeron  @rmccallum81 @ryanm-pm.

By the way, there is no way moleculer tests catch this change because tests do not use ts type definitions.

**Comment by icebob** [comment]
Moleculer has typescript test because there was some syntax error in d.ts file in early PRs: https://github.com/moleculerjs/moleculer/tree/master/test/typescript/hello-world
Maybe we should extend it with other new cases.

**Comment by rmccallum81** [comment]
I don't think that type definition changes should cause a version change except as a patch since they don't affect the code. If there's a change to the types that will be breaking for existing code, it should wait for a major version update if possible. Since moleculer is still under `1.0.0` it can make this type of change with a patch or minor version update.

**Comment by faeron** [comment]
I think I second @rmccallum81's opinion.
We also have it stated in the [docs](https://moleculer.services/docs/0.13/#Versioning), that until `1.0.0` breaking changes will be released minor updates.

**Comment by fugufish** [comment]
I have to disagree. Any change that requires a developer to alter their code to switch from one version to the next should be considered a breaking change. Though minor, most developers peg their package versions to the minor (`^13.5`), if automated builds fail due to changes in the type definitions that is a breaking change (as far as the definition goes).

while I understand that the docs state that breaking changes will be released with minor updates, I have noted that a great deal of care has been taken to ensure that they do not for the most part, I myself have submitted PRs to alter the typings, and was explicitly asked to ensure backwards compatibility, so in that I'm sorry for my confusion.
