### ISSUE TITLE
AMQP - autoDelete not working as expected

### ISSUE THREAD

**Issue by omerts** [moleculerjs/moleculer#532]
Hey,

Thanks for this amazing lib, really amazing!
1) autoDelete doesn't actually set all the queues created to have an expiry
2) IMHO isn't it better to just define the autoDelete flag on the queue instead of giving the queue and expiry?

![image](https://user-images.githubusercontent.com/4996164/57588369-e8b12100-751b-11e9-8994-b9707a196d43.png)

This is my config:
![image](https://user-images.githubusercontent.com/4996164/57588372-f49ce300-751b-11e9-9ab4-76f571844efa.png)

**Comment by icebob** [comment]
I think it's conscious in case of disabled balancer, right @Nathan-Schwartz ?

**Comment by Nathan-Schwartz** [comment]
@icebob Yes, that's correct.

@omerts Node IDs are intended to be unique, so when a node goes down we assume that all of the nodeID specific queues are not needed (since the NodeID might never be used again).

RabbitMQ's queue autodelete will remove a queue as soon as there are no consumers, even if the queue still has messages in it.

REQB and EVENTB are special because they allow nodes with different NodeIDs to pull from the same queue. It could be harmful to delete these queues because even if all the nodes are down, the messages could still be processed when a new node comes up.

You can find the some discussion and reasonings about this topic in this [thread](https://github.com/moleculerjs/moleculer/pull/341)

**Comment by omerts** [comment]
@icebob @Nathan-Schwartz Thanks for the detailed anwer. Clear now.
