### ISSUE TITLE
custom error

### ISSUE THREAD

**Issue by radical-edo** [moleculerjs/moleculer#579]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [ + ] I am running the latest version
- [ + ] I checked the documentation and found no answer
- [ + ] I checked to make sure that this issue has not already been filed
- [ + ] I'm reporting the issue to the correct repository

## Current Behavior

I throw my own custom error that I have implemented

```ts
export class ValidationError extends Moleculer.Errors.MoleculerError  {
  constructor(data: ValidationDetail[]) {
    super('Incorrect payload', 400, 'VALIDATION_ERROR', data);
  }
}
```
Problem is that the code is still set to `422` not `400`. No idea why. Although I've noticed that if I change the `name` of the error to the base class, the code will be `400` as provided.
Something along the lines:

```ts
export class ValidationError extends Moleculer.Errors.MoleculerError implements ActionError {
  public name: string = Moleculer.Errors.MoleculerError.name;
  constructor(data: ValidationDetail[]) {
    super('Incorrect payload', 400, 'VALIDATION_ERROR', data);
  }
}
```

Also, this one is written in TS ver `3.3.3333`. No idea if that's an issue

## Expected Behavior

I'd expect the code be changed from `422` to `400`

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Call any action
2. throw a custom error defined as above

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Moleculer version: 0.13.9
* NodeJS version: 10.15.3
* Operating System: Alpine Linux v3.9.2  (run in a docker container on MacOS 10.14.5)

**Comment by AndreMaz** [comment]
I've tried here got the following result
![image](https://user-images.githubusercontent.com/9802754/62410169-246afc80-b5da-11e9-98c2-89212f094b6e.png)

**Comment by dkuida** [comment]
@AndreMaz  funny enough - the error is because you used a status code 123 which doe not exist.

here is your code that return the expected behavior
```typescript
import * as moleculer from 'moleculer';
import { Service, Action } from 'moleculer-decorators';
import * as ApiGateway from 'moleculer-web';

const {ServiceBroker, Errors} = moleculer;

class ValidationError extends Errors.MoleculerError {

    constructor(data) {
        super('Payload error', 123, 'PAYLOAD_ERROR', data);
    }
}

@Service({})
class Hello extends moleculer.Service {

    @Action({
    })
    public async error(_ctx: moleculer.Context) {
        return Promise.reject(new ValidationError({anotherData: 'custom error'}))
    }
}

@Service({
    mixins: [ApiGateway],
    routes: [{whitelist: '**'}],
    settings: {port: 3000}
})
class Api extends moleculer.Service {

}

const broker = new ServiceBroker();
broker.createService(Hello);
broker.createService(Api);
broker.start().then(() => broker.repl());
```
{
  "name": "ValidationError",
  "message": "Payload error",
  "code": 400,
  "type": "PAYLOAD_ERROR",
  "data": {
    "anotherData": "custom error"
  }
}
same when I am passing an array as a parameter.

I think you got 422 from some other parameters needed for your Action before you reached the rejection

**Comment by AndreMaz** [comment]
I still don't fully understand what kind of error we are talking about. The HTTP status code? or the error produced by `class ValidationError extends Errors.MoleculerError {}`?

If we are talking about `ValidationError` then the 123 code is a valid (as any other number). _It wouldn't have any semantic meaning but it is valid_
The resulting HTTP `500 Internal Server Error` is also correct because Moleculer will try to use ValidationError's code as HTTP status code. It ValidationError is an invalid HTTP code then the status code is set to 500. _This is what happened with status code 123_

Setting `ValidationError` with a `4xx` code will result in HTTP status code equal to the one present in ValidationError.
![image](https://user-images.githubusercontent.com/9802754/64023858-0f2db300-cb31-11e9-8769-e51fefc9036b.png)

If the goal is to set the HTTP status code to some custom value then we could use the `ctx.meta.$statusCode`
![image](https://user-images.githubusercontent.com/9802754/64024616-b5c68380-cb32-11e9-80cc-a5cf197b832d.png)

**Comment by dkuida** [comment]
> If the goal is to set the HTTP status code to some custom value then we could use the `ctx.meta.$statusCode`

I think this is exactly what @radical-edo wanted to achieve. but using custom Error, rather than manually writing the statusCode every time. for a homogeneous response.

@radical-edo could you elaborate
