### ISSUE TITLE
Don't swallow event exceptions

### ISSUE THREAD

**Issue by adam-mccormick** [moleculerjs/moleculer#605]
**Is your feature request related to a problem? Please describe.**
I am trying to implement a transporter that can ensure durable events using queues. When an event handler throws an exception it is swallowed and logged in the event catalog. This prevents the transporter from knowing if an event has actually been handled.

**Describe the solution you'd like**
If exceptions were propagated down to the transporter then we can implement the logic for what should be done with incoming messages that cause an exception.

**Additional context**
For context, I am deploying my application to AWS and want to take advantage of SNS and SQS. I implemented a custom transporter for this but I lose some of its features due to this problem (i.e I could leave messages on the queue for processing later if an event handler throws an exception)

**Comment by icebob** [comment]
And what you will do, when there are 3 event listeners on the same event name on the same node and only one throw error in the handler, other two processed the event. In this case, you will retry or drop? It is a more complicated issue. This is why action calling has a timeout & retry features, and the event is a fire & forget solution. 
When you call service action, it will be called only one handler.
When you emit an event, you don't know how many handlers will get it and process it.

If you want to store an event, middleware can be a good solution. Because you can wrap the `broker.emit` &`broker.broadcast` methods. In the middleware, store the events and after send further with the original methods.

**Comment by adam-mccormick** [comment]
I agree but I think handling duplicate messages is a much simpler problem to solve in the application than guaranteed delivery would be (hence why I am using SQS). 

To be clear I'm not suggesting changes to the event API or that Moleculer should inherently do anything differently, only that transporters can be aware that an exception was thrown and _potentially_  take action.

**Comment by icebob** [comment]
I think [event acknowledgement](https://github.com/moleculerjs/rfcs/issues/2) can solve this problem and not if we place business logic into the transporter logic to decide what it does with the failed events.
