### ISSUE TITLE
Channel reconnect feature?

### ISSUE THREAD

**Issue by Somebi** [moleculerjs/moleculer#692]
https://github.com/moleculerjs/moleculer/blob/cb4ceafaf8ad30bf6d5962999bc3d2cdb73a478f/src/transporters/amqp.js#L179

I'm missing something or you are not re-connecting channel on close and on error you do nothing.
Even if it's not graceful case...

Please explain. Thank you.

**Comment by icebob** [comment]
ping @Nathan-Schwartz

**Comment by Nathan-Schwartz** [comment]
@Somebi Good question! That's correct. 

The re-connection logic happens at the connection level and not the channel level. This is because both the channel's and connection's close handlers will fire if a connection is lost. In this case everything recovers as expected.

Your questions raises a potential issue where the channel closes without the connection going down, and you are correct that the channel won't reconnect in this case.

Are you encountering this issue? I haven't been able to produce this behavior before, so a repro repo would help verify a fix.

That said, I suspect `this.connection.close().then(reject)` in the channel close handler would do the trick.
