### ISSUE TITLE
Global error handler called multiple times

### ISSUE THREAD

**Issue by iredjee** [moleculerjs/moleculer#704]
**Steps to reproduce**

1. Create new project with API Gateway `moleculer init project demo`
2. Add new action in "greeter" service, e.g. smth like
```
boom: {
  rest: {
    method: "GET",
    path: "/boom"
  },
  handler() {
    throw new Errors.MoleculerError("oooops", 400, "BOOM");
  },
},
```
3. Add global error handler in "moleculer.config.js"
```
errorHandler(err, info) {
  this.logger.warn("Error handled:", err);
  throw err;
},
```
4. Run project yarn start
5. Open endpoint `api/greeter/boom` in browser
6. in console "Error handled" message is logged twice.

Tried to debug a bit, found that every action is wrapped with errorHandler middleware. And I've found that httpHandler first calls this.actions.rest (which is wrapped with errorHandler middleware) and then it calls greeter.boom action (which is also wrapped with errorHandler middleware). And both go to global errorHandler at the end, so that we have 2 logs.

**Actual**

Global error handler called multiple times

**Expected**

Global error handler called only once

**Comment by icebob** [comment]
I don't think it's wrong because if you run the greeter service on node1, and api gateway service on node2, in this case, the `errorHandler` will be called on both nodes because the error is thrown further and not handled, so the error goes back to the caller. In your case, both services are running locally, but the logic is the same.

**Comment by iredjee** [comment]
Makes sense! Thanks @icebob , closing the issue
