### ISSUE TITLE
Event Durability 

### ISSUE THREAD

**Issue by NickClark** [moleculerjs/moleculer#724]
**Is your feature request related to a problem? Please describe:**

We want to be able to have durable events. Guarantees that no matter what, a given event will be held till someone handles it. I've been working on moving a codebase (that was using custom events in RabbitMQ) to Moleculer, and while many events and actions are ok if there's a critical failure, some are not.

**Describe the solution you'd like:**

It would be nice if we could define some events as *durable* to ensure they eventually get handled, even in the case of system failure.

**Comment by Wallacy** [comment]
I have this 'kind' of events on my system, but is very, very particular for our use. Basiscally we broadcast a lock to everyone, then we put a this info on our database, and all services need to handle and remove the lock individually.

It's more complex than that, but that's the idea.

**Comment by icebob** [comment]
Durability of event is not a simple problem and many project should many custom logic. I don't think so that there is a common solution which will be good for everyone. If somebody want to do durability, he can do it with middleware wrapping `emit`,`broadcast` and `localEvent` hooks. If somebody has a solution in a middleware, please share it in the [awesome repo](https://github.com/moleculerjs/awesome-moleculer).
