### ISSUE TITLE
Separate Moleculer components from each other.

### ISSUE THREAD

**Issue by erfanium** [moleculerjs/moleculer#728]
I used Moleculer for several months, But I had problems with its structure, that I decided not to use Moleculer at the moment. and I couldn't fix them alone

The biggest problem is, Moleculer components are completely interdependent, This makes it very difficult to test/extend/DependencyInjection the components.

We have 4 major components, ServiceBroker, Services, Actions, Events. They must completely separated. Service must work without real broker, Action must work without real service.

This is my new project structure that solves these problems:

```ts
// users/actions/login.ts
export default function (service: Service): Action<Req, Res> {
   const sendSms = service.useService("sms.send")
   return new Action<Req, Res>({
      name: "login",
      params: {},
      handler(params, ctx) {
           // code
           sendSms({ phone: '123' })  // calling another service
      }
  })
}

// user.service.ts
export default function (broker: Broker): Service {
   const users = new Service(broker, 'users')
   users.action(login)
   return users
}

// main.ts
const broker = new Broker()
const broker.addService(users)
```
Singleton Pattern is what that Moleculer needs
Can we migrate to this design pattern?

**Comment by icebob** [comment]
I don't think so, because it completely changes the current service schema & structure.
Maybe you can do it yourself if you create an own `Service` class which does the service registration based on your structure.
You should create the same service spec structure what `parseServiceSchema` does and call the `this.broker.registerLocalService(serviceSpecification);` when the service started.
