### ISSUE TITLE
AMQP 1.0 transporter issue on CI server

### ISSUE THREAD

**Issue by icebob** [moleculerjs/moleculer#733]
Hi @vladir95,

I've made some integration tests with Docker & Kubernetes and it generates & starts a simple Moleculer project with all transporters. All are good, except the AMQP1.0 transporter. And I don't understand what is the problem. Could you help me to check, what is the problem with it?

Here is the log of ActiveMQ container:
https://github.com/moleculerjs/moleculer-template-project/runs/656329054?check_suite_focus=true#step:13:45

It runs more containers, but only one transporter:
```
       Name                     Command               State                               Ports                            
---------------------------------------------------------------------------------------------------------------------------
ci-test_activemq_1   /bin/sh -c bin/activemq co ...   Up      1883/tcp, 5672/tcp, 61613/tcp, 61614/tcp, 61616/tcp, 8161/tcp
ci-test_api_1        docker-entrypoint.sh npm start   Up                                                                   
ci-test_greeter_1    docker-entrypoint.sh npm start   Up                                                                   
ci-test_mongo_1      docker-entrypoint.sh mongod      Up      27017/tcp                                                    
ci-test_products_1   docker-entrypoint.sh npm start   Up                                                                   
ci-test_redis_1      docker-entrypoint.sh redis ...   Up      6379/tcp                                                     
ci-test_traefik_1    /entrypoint.sh --api.insec ...   Up      0.0.0.0:3000->80/tcp, 0.0.0.0:3001->8080/tcp           
```
Here is the ActiveMQ container in [compose](https://github.com/moleculerjs/moleculer-template-project/blob/master/template/docker-compose.yml):
```yml
  activemq:
    image: rmohr/activemq
    networks:
      - internal
```
And ServiceBroker connects to them as `TRANSPORTER=amqp10://guest:guest@activemq:5672`

Thanks in advance!

**Comment by vladir95** [comment]
Hey @icebob,
https://github.com/moleculerjs/moleculer-template-project/pull/20 fixes that.
Basically the issue was that amqp container didnt finish loading in time for the brokers to connect, but it did connect them after it finished loading. The brokers already received the 'Failed to connect' status from the first connection request, and tried to reconnect, even though the amqp server already considered them connected.
I added a healthcheck and updated the depends_on fields to wait for the amqp server to finish loading. The healthcheck depends_on field is only supported in docker_compose V2, that why there is a conditional check on the top.

Hope this helps 🙂

**Comment by icebob** [comment]
Thanks @vladir95 I will check the PR!
