### ISSUE TITLE
ActionParams type doesn't allow $$strict: 'remove' option

### ISSUE THREAD

**Issue by artem-khromov** [moleculerjs/moleculer#759]
ActionParams object values are restricted to string constants, boolean or ActionParamTypes.
Adding string type should fix this issue (or at least adding "remove" string constant).

https://github.com/moleculerjs/moleculer/blob/47722072f2f39bbbca9b91654073f39b886df33c/index.d.ts#L49-L66

**Comment by AndreMaz** [comment]
I think that this issue is caused by `fastest-validator` v1. It introduced some changes but we didn't update the `ActionParamTypes`. Adding `string` type would solve the issue but if we do this then `string` constants would become meaningless. 

There is also an issue with the [shorthand notation](https://github.com/icebob/fastest-validator#shorthand-definitions):

```js
const schema = {
    password: "string|min:6",
    age: "number|optional|integer|positive|min:0|max:99", // additional properties
    state: ["boolean", "number|min:0|max:1"] // multiple types
}
```
TS complains about it:
![image](https://user-images.githubusercontent.com/9802754/78175909-8f175500-7453-11ea-8857-7bacfea0a11f.png)


I don't have enough knowledge about TS so I don't know what is the best solution to handle this issue.
@shawnmcknight what do you think about this?

This issue also blocks https://github.com/moleculerjs/moleculer-template-project-typescript/pull/20

**Comment by shawnmcknight** [comment]
@AndreMaz Unfortunately there is no way to have any sort of pattern matching or regex on strings (see [issue](https://github.com/microsoft/TypeScript/issues/6579)).  It makes the shorthand definitions somewhat impossible to type cleanly.

The other issue here is that, because validators are extensible, the types as defined here are not necessarily ever going to be correct, and type aliases cannot be augmented in the way that interfaces and classes can be.  It's likely that the best approach here would be to use fastest-validator's types by default, but allow for augmentation (which requires an interface in this case) for when it doesn't apply.  I'm sure some additional work is likely needed in fastest-validator to make that transition cleanly as well.
