### ISSUE TITLE
Passing data to Service while loading it

### ISSUE THREAD

**Issue by Kamil93** [moleculerjs/moleculer#859]
Let's say we have `Service` and we want to load it by `ServiceBrokers` in serveral `Nodes`. In each `Service`, we need to do little change based on some provided `data` while using `broker.loadService("./math.service.js");`

The only thing that came to my mind is setting in **ServiceBroker js script file** some data in `global` variable of node.js and then read it in **Service js script file**.

But maybe there is a better solution? Without using global scope? Something like:

`broker.loadService("./math.service.js", {someCustomData: 123});`

Or maybe we could use `mixins`, like **root service file** and **children service files** with some data change in `schema`, but does **lifecycle events/methods of service** through mixins **are called also**?

This table doesn't say anything about **lifecycle events**: https://moleculer.services/docs/0.14/services.html#Merge-algorithm

**Comment by ccampanale** [comment]
> Let's say we have Service and we want to load it by ServiceBrokers in serveral Nodes. In each Service, we need to do little change based on some provided data while using broker.loadService("./math.service.js");

It sounds like you want to to do something when the service is `created()` whereby the configuration of the resulting service is modified based on how it was started, so I would suggest using a combination of mixins and lifecycle events.

> This table doesn't say anything about lifecycle events: https://moleculer.services/docs/0.14/services.html#Merge-algorithm

I believe it does though; `created`, `started`, and `stopped` listeners will be concatenated, i.e. they will be applied in the order they appear within the schema and it's mixins.

Let me know if I'm missing something.

Another option I've toyed around with personally is using a custom class which ultimately generates a service schema to be provided to the broker for starting but can be used to accomplish essentially what you have described.

```
broker.createService(
  MyModule.CustomClass(require("./math.service.js"), {someCustomData: 123}).getServiceSchema()
);
```

This is example uses `createService()` instead of `loadService()`. You could imagine that a custom class could load a service from file using `require` (or other options), be provided data upon construction which is uses to manipulate the loaded schema, and which is thus returned via `getServiceSchema()`. 

I still think you could accomplish the same by leveraging mixins and lifecycle events though.

**Comment by Kamil93** [comment]
> I still think you could accomplish the same by leveraging mixins and lifecycle events though.

I think this will be the best way, because when u use `createService()` hot reload wont work

**Comment by AndreMaz** [comment]
Closing as this issue seems to be solved. Feel free to reopen if needed
